default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres # Replace with your PostgreSQL username
  password: 123456   # Replace with your PostgreSQL password

development:
  <<: *default
  database: billetto_development

test:
  <<: *default
  database: billetto_test

production:
  <<: *default
  database: billetto_production
  username: postgres # Replace with the production username
  password: 123456   # Replace with the production password
